- name: Ensure /opt/einsatzmonitor exists
  file:
    dest: /opt/einsatzmonitor
    mode: 0755
    state: directory
    owner: pi
    group: pi

- name: Download einsatzmonitor release
  get_url:
    url: "{{ einsatzmonitor_download_url }}"
    dest: /opt/einsatzmonitor/einsatzmonitor_release.zip
    mode: 0755
    force: 'yes'
  notify:
    - restart einsatzmonitor

- name: Extract einsatzmonitor_release.zip into /opt/einsatzmonitor
  command: "/usr/bin/unzip -qq -o /opt/einsatzmonitor/einsatzmonitor_release.zip -d /opt/einsatzmonitor"
  args:
    warn: 'no'

- name: Ensure file permissions are set to pi:pi
  file:
    dest: /opt/einsatzmonitor
    mode: 0755
    state: directory
    recurse: 'yes'
    owner: pi
    group: pi

- name: install einsatzmonitor systemd unit file
  template: src=einsatzmonitor.service.j2 dest=/etc/systemd/system/einsatzmonitor.service

- name: start einsatzmonitor systemd service
  systemd: state=started name=einsatzmonitor daemon_reload=yes